### GET all blogs
GET http://localhost:3003/api/blogs

###

### CREATE blog (válido)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Primer blog",
  "author": "Pepe",
  "url": "https://ejemplo.com",
  "likes": 5
}

###

### CREATE blog (sin title -> ERROR)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Pepe",
  "url": "https://ejemplo.com"
}

###

### CREATE blog (sin url -> ERROR)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog sin URL",
  "author": "Pepe"
}

###

### UPDATE blog (cambia likes)
PUT http://localhost:3003/api/blogs/REEMPLAZA_ID
Content-Type: application/json

{
  "title": "Primer blog actualizado",
  "author": "Pepe",
  "url": "https://ejemplo.com",
  "likes": 999
}

###

### DELETE blog
DELETE http://localhost:3003/api/blogs/REEMPLAZA_ID