### GET all users
GET http://localhost:3003/api/users

###

### CREATE user (válido)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "pepe123",
  "name": "Pepe García",
  "password": "secret123"
}

###

### CREATE user (sin password -> ERROR)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "sinpass",
  "name": "Error User"
}

###

### CREATE user (password corto -> ERROR)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "shortpass",
  "name": "Error User",
  "password": "ab"
}

###

### CREATE user (username duplicado -> ERROR)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "pepe123",
  "name": "Duplicado",
  "password": "secret123"
}