### GET all users
GET http://localhost:3003/api/users

###

### CREATE user (válido)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Juan123",
  "name": "Juan García",
  "password": "secret123"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "123",
  "name": "123",
  "password": "123"
}




