POST http://localhost:3001/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGUiLCJpZCI6IjZhMzE0NzJjMGUwYjRlNmI0ZTBhOTMzZCIsImlhdCI6MTc4MTYyMjg1NX0.C8ehQF7jTYLnKeJXdqNck2ysS9a_uGl3O9r_9KwnGuk
Content-Type: application/json

{
  "content": "Nota de Juan 3",
  "important": true
}